name: Push Notification

on: push

jobs:
  notify:
    uses: conradtondryk/github-bot/.github/workflows/notify-telegram.yml@master
    secrets:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
